dist: trusty 
sudo: required 
language: cpp
compiler: g++-7

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-7

notifications:
 email:
  on_success: never
  on_failure: always

before_install: sudo apt update -qq

before_script:
    - sudo apt-get install libsfml-dev
script:
    - mkdir build && cd build
    - cmake ..
