dist: trusty
sudo: required 
language: cpp
compiler: g++
install: export CXX="g++-5"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

notifications:
 email:
  on_success: never
  on_failure: always

before_install: sudo apt-get update -qq

before_script:
  - wget http://sfml-dev.org/download/sfml/2.1/SFML-2.1-linux-gcc-64bits.tar.bz2 -O /tmp/sfml.tar.bz2
  - tar -xjvf /tmp/sfml.tar.bz2
  - sudo cp -r SFML-2.1/* /usr/
  - sudo apt-get install -y libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1 
script:
    - make
