dist: trusty 
sudo: required 
language: cpp
compiler: g++-7

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-7

notifications:
 email:
  on_success: never
  on_failure: always

before_install: 
    - sudo apt update -qq
    - sudo apt upgrade

before_script:
    - sudo apt install libsfml-dev
    - sudo apt-get install cmake 
script:
    - mkdir build && cd build
    - cmake ..
