dist: bionic 
sudo: required 
language: cpp
compiler: g++

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-7

notifications:
 email:
  on_success: never
  on_failure: always

before_install: sudo apt-get update -qq

before_script:
    - sudo apt-get install libsfml-dev
script:
    - make
