dist: trusty 
sudo: required 
language: cpp
compiler: g++-7

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-7

notifications:
 email:
  on_success: never
  on_failure: always

before_install: sudo apt update -qq

before_script:
    - wget https://www.sfml-dev.org/files/SFML-2.4.2-linux-gcc-64-bit.tar.gz
    - sudo tar zxvf SFML-2.4.2-linux-gcc-64-bit.tar.gz -C /usr/local
    - sudo apt-get install cmake 
script:
    - mkdir build && cd build
    - cmake ..
